import { ShowBadge } from './constants';

export const cieloData = {
  menu: [
    { id: "co1", cat: "COCKTAILS", nombre: "Buenos Aires Sour", desc: "Whisky, limón, clara de huevo y espuma de Malbec. El emblema de la carta.", precio: 6500, badges: ["RECOMENDADO"] },
    { id: "co2", cat: "COCKTAILS", nombre: "Cielo Negroni", desc: "Gin premium, vermouth rosso, Campari y twist de naranja flameada.", precio: 7200, badges: ["MÁS PEDIDO"] },
    { id: "co3", cat: "COCKTAILS", nombre: "Palermo Spritz", desc: "Aperol, prosecco, soda y naranja fresca. Vista de la ciudad incluida.", precio: 5800 },
    { id: "co4", cat: "COCKTAILS", nombre: "Rooftop Mule", desc: "Vodka artesanal, jengibre fresco, lima y ginger beer premium.", precio: 6200 },
    { id: "co5", cat: "COCKTAILS", nombre: "Sin Altura", desc: "Mocktail de pepino, menta, limón y agua con gas. Refrescante y elegante.", precio: 4500, badges: ["VEGANO"] },
    { id: "v1", cat: "VINOS", nombre: "Malbec Gran Reserva", desc: "Mendoza. Notas a frutos rojos, tabaco y chocolate. Copa o botella.", precio: 4200, badges: ["RECOMENDADO"] },
    { id: "v2", cat: "VINOS", nombre: "Torrontés Seco", desc: "Salta. Floral, fresco, ideal para el verano en el rooftop.", precio: 3800 },
    { id: "v3", cat: "VINOS", nombre: "Champagne Nacional", desc: "Brut rosé, burbuja fina. Bienvenida perfecta.", precio: 8500 },
    { id: "t1", cat: "TAPAS", nombre: "Burrata con Tomates Cherry", desc: "Burrata fresca, tomates cherry asados, albahaca y aceite de oliva premium.", precio: 7800, badges: ["RECOMENDADO"] },
    { id: "t2", cat: "TAPAS", nombre: "Tabla Ibérica", desc: "Jamón ibérico, chorizo español, queso manchego y membrillo.", precio: 12500, badges: ["MÁS PEDIDO"] },
    { id: "t3", cat: "TAPAS", nombre: "Ceviche de Lenguado", desc: "Lenguado fresco, leche de tigre, maíz tostado y cilantro.", precio: 9200 },
    { id: "t4", cat: "TAPAS", nombre: "Sushi Roll Cielo", desc: "4 piezas de roll de salmón con palta y salsa de la casa.", precio: 8800 },
  ],
  shows: [
    {
      id: "sh1",
      nombre: "DJ Set — Sábado Electrónico",
      genero: "Electrónica / House",
      fecha: new Date(2026, 5, 14),
      horario: "22:00",
      entrada: 0,
      lugaresDisponibles: 35,
      descripcion: "El mejor DJ set de la ciudad desde el piso 18. Vista panorámica, sonido premium.",
      badge: ShowBadge.DISPONIBLE,
      imagen: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=800",
    },
    {
      id: "sh2",
      nombre: "Jazz Nocturno",
      genero: "Jazz / Soul",
      fecha: new Date(2026, 5, 19),
      horario: "21:00",
      entrada: 2500,
      lugaresDisponibles: 2,
      descripcion: "Una noche íntima de jazz con vista a Buenos Aires. Cupos muy limitados.",
      badge: ShowBadge.ULTIMOS_LUGARES,
      imagen: "https://images.unsplash.com/photo-1415201364774-f6f0bb35f28f?w=800",
    },
    {
      id: "sh3",
      nombre: "Noche Latina — DJ Colombiano",
      genero: "Latina / Urbano",
      fecha: new Date(2026, 5, 21),
      horario: "23:00",
      entrada: 0,
      lugaresDisponibles: 60,
      descripcion: "El mejor DJ de Bogotá en Buenos Aires. Solo una noche.",
      badge: ShowBadge.DISPONIBLE,
      imagen: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800",
    },
  ],
  resenas: [
    { id: "r1", nombre: "Camila B.", rating: 5, texto: "El Buenos Aires Sour es una obra de arte. La vista desde el piso 18 es simplemente impresionante.", fecha: "hace 1 día" },
    { id: "r2", nombre: "Andrés M.", rating: 5, texto: "Llevé a mi novia por su cumpleaños. El pack VIP superó todas las expectativas. Volvemos seguro.", fecha: "hace 3 días" },
    { id: "r3", nombre: "Florencia K.", rating: 5, texto: "La tabla ibérica y el Negroni son la combinación perfecta. El DJ del sábado estuvo increíble.", fecha: "hace 1 semana" },
    { id: "r4", nombre: "Tomás P.", rating: 4, texto: "Lugar único en Buenos Aires. Los precios son acordes a la calidad y la experiencia.", fecha: "hace 2 semanas" },
    { id: "r5", nombre: "Julieta A.", rating: 5, texto: "El mejor rooftop de la ciudad sin dudas. La atención es de 10.", fecha: "hace 1 mes" },
  ],
  galeria: [
    { id: "g1", cat: "Vista", src: "https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=800", alt: "Vista nocturna de Buenos Aires desde el rooftop" },
    { id: "g2", cat: "Cocktails", src: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=800", alt: "Buenos Aires Sour — cocktail de autor" },
    { id: "g3", cat: "Cocktails", src: "https://images.unsplash.com/photo-1470338745628-171cf53de3a8?w=800", alt: "Bartender preparando cocktail" },
    { id: "g4", cat: "Ambiente", src: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800", alt: "Living VIP con vista a la ciudad" },
    { id: "g5", cat: "Comida", src: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800", alt: "Tapas gourmet de autor" },
    { id: "g6", cat: "Eventos", src: "https://images.unsplash.com/photo-1540575467537-61b5a31acef2?w=800", alt: "Evento privado exclusivo en el rooftop" },
    { id: "g7", cat: "Vista", src: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=800", alt: "Noche de DJ en Cielo Rooftop" },
    { id: "g8", cat: "Ambiente", src: "https://images.unsplash.com/photo-1578474846511-04ba529f0b88?w=800", alt: "Barra premium con iluminación dorada" },
  ],
  usuario: {
    nombre: "Valentina R.",
    puntos: 1200,
    nivel: "CIELO VIP",
    proximoNivel: "CIELO BLACK",
    faltanPuntos: 800,
    historial: [
      { fecha: "05/06/2025", desc: "DJ Set Sábado + Living VIP", puntos: 300 },
      { fecha: "28/05/2025", desc: "Jazz Nocturno + cocktails", puntos: 250 },
      { fecha: "14/05/2025", desc: "Noche VIP Pack", puntos: 400 },
      { fecha: "01/05/2025", desc: "Cumpleaños exclusivo", puntos: 250 },
    ],
  },
};
